spring:
  application:
    name: micoserice-zipkin-server
server:
  port: 9994
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
